[package]
name = "bare_metal"
version = "0.1.0"
edition = "2024"

[dependencies]
#bootloader = "0.11.13"
bootloader = "0.9"
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"


[[bin]]
name = "bare_metal"
test = false
bench = false
